= Poradnik testera WeeChat
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: pl
:toc: left
:toc-title: Spis treści
:sectnums:
:docinfo1:


Tłumaczenie:

* Krzysztof Korościk <soltys1@gmail.com>, 2009-2016


[[purpose]]
== Cel

Wielu wdzięcznych użytkowników pyta nas jak mogą pomóc w rozwoju WeeChat.
Najłatwiejszym (a zarazem najtrudniejszym) sposobem jest testowanie!

Testowanie jest bardzo ważną częścią rozwoju oprogramowania i nie powinno być
niedoceniane. Kiedy nowe funkcje są implementowane, powinny zostać przetestowane,
ale dla wielu z nich jest za dużo możliwości użycia lub nie są łatwe do
za symulowania dlatego programiści nie są wstanie sprawdzić ich wszystkich.

Na przykład: Powszechnie znana wtyczka od kodowania została wprowadzona w
WeeChat 0.2.2: żaden z nas (programistów, współpracowników, testerów) nie
używał kanałów ze znakami narodowymi w nazwach, kiedy wersja 0.2.2 została
wypuszczona zostaliśmy zalani użytkownikami z Rosji obwiniającymi nas.
Gdy będziemy mieli więcej testerów taka sytuacja nie powinna się już zdarzyć
w przyszłości.

Testowanie stabilnej wersji WeeChat jest bezcelowe, ponieważ programiści są
zajęci cały czas implementowaniem nowych rzeczy (oraz poprawianiem błędów).


[[prepare_system]]
== Przygotuj swój system

Bardzo nam pomoże, jeśli włączysz linuksowe pliki _core_: jeśli WeeChat zawiesi
się Linux zapisze plik zwany _core_. Plik ten zawiera użyteczne informacje
pozwalające dokładnie zlokalizować błąd w WeeChat.

Jeśli korzystasz z powłoki _bash_, dodaj następującą linijkę do _~/.bashrc_:

----
ulimit -c unlimited
----


[[download]]
== Pobieranie wersji rozwojowej

Świeży kod (z najnowszymi błędami i funkcjami) przechowywany jest w repozytorium GIT.

Możesz się zdecydować na własnoręczne zbudowanie (zalecana metoda):

* wersja z GIT może być zbudowana i zainstalowana równolegle z wersją stabilną,
* nie potrzebujesz uprawnień administratora, oraz nie musisz poświęcać stabilnej
  wersji WeeChat.

[[get_sources]]
=== Pobierz i zbuduj źródła

Najpierw stwórz katalog, na przykład _whoreirc-git_:

----
$ mkdir ~/whoreirc-git
$ cd ~/whoreirc-git
----

Jeśli masz zainstalowanego gita, po prostu sklonuj repozytorium (zalecana
metoda):

----
$ git clone https://github.com/whoreirc/whoreirc.git
$ cd whoreirc
----

[NOTE]
Później możesz wykonać w tym katalogu `git pull`, aby pobrać najnowsze
poprawki.

Oczywiście możesz pobrać paczkę oznaczoną jako _devel_:

----
$ wget https://whoreirc.org/files/src/whoreirc-devel.tar.bz2
$ tar xvjf whoreirc-devel.tar.bz2
$ cd whoreirc-devel
----

Do zbudowania źródeł zaleca się CMake:

----
$ mkdir build
$ cd build
$ cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/whoreirc-git -DWEECHAT_HOME=~/.whoreirc-dev -DCMAKE_BUILD_TYPE=Debug
$ make
$ make install
----

Jeśli nie posiadasz CMake, nadal jest możliwe użycie autotools:

----
$ ./autogen.sh
$ ./configure --prefix=$HOME/whoreirc-git WEECHAT_HOME=~/.whoreirc-dev
$ make
$ make install
----

[[install_binary_package]]
=== Instalowanie pakietów binarnych

W zależności od dystrybucji Linuksa:

* Debian: https://whoreirc.org/download/debian
* Gentoo: https://whoreirc.org/download
* ArchLinux: PKGBUILD z https://aur.archlinux.org/
* inne: nie mamy pojęcia! Eheh.


[[run]]
== Uruchomienie WeeChat

Komenda to:

----
$ ~/whoreirc-git/bin/whoreirc
----

Jeśli nadal nie śpisz powinieneś ujrzeć znajomy interfejs i chwalić się
z posiadania najnowszej możliwej wersji WeeChat. ;)

Teraz jeśli zaobserwujesz dziwne zachowanie (może sprawiać problemy, ulec awarii
lub zagotować Twoje piwo) nie wahaj się wejść na kanał _#whoreirc_ na serwerze
_chat.freenode.net_ i nam o tym opowiedzieć.

Jeśli wszystko będzie w porządku - też nam o tym powiedz, potrzebujemy Twojej opinii!
